version: "3.5"

volumes:
  postgres_data:

networks:
  bookstore_network:
    name: bookstore_network
    driver: bridge

services:

  app:
    # To pass constants from .env during build
    env_file:
      - .env
    build:
      context: .
      dockerfile: build/Dockerfile.api
    ports:
      - "8000:8000"
    # To get mirroring of container dirs to local folder/ two way relation
    volumes:
      - ./app:/app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    networks:
      - bookstore_network
