version: "3.5"

volumes:
  postgres_data:

networks:
  bookstore_network:
    name: bookstore_network
    driver: bridge

services:

  app:
    # To pass constants from .env during build
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: build/Dockerfile.api
    container_name: api
    restart: always
    ports:
      - "8000:8000"
    # To get mirroring of container dirs to local folder/ two way relation
    volumes:
      - ./app:/app
    depends_on:
      - db
    networks:
      - bookstore_network
  
  db:
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: build/Dockerfile.db
    container_name: database
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # Fetch from .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    networks:
      - bookstore_network
